/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AnimalExternalHistoryFrame.java
 *
 * Created on 13-Mar-2014, 22:44:46
 */

package my.zooProjectPackage;
// import my.animalLibraryPackage.Animal;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author patrick
 */
public class AnimalExternalHistoryFrame extends javax.swing.JFrame {
    private PreparedStatement prest;


    private String Ayear="####";
    private String Amonth="##";
    private String Aday="##";
    private String DOB=Ayear+"-"+Amonth+"-"+Aday;

    /** Creates new form AnimalExternalHistoryFrame */
    public AnimalExternalHistoryFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        animalExternalHistoryPanel = new javax.swing.JPanel();
        previousLocationLabel = new javax.swing.JLabel();
        dateArrivedLabel = new javax.swing.JLabel();
        dateDepartedLabel = new javax.swing.JLabel();
        departedToLabel = new javax.swing.JLabel();
        dateDeceasedLabel = new javax.swing.JLabel();
        previousLocationText = new javax.swing.JTextField();
        departedToText = new javax.swing.JTextField();
        yearLabel = new javax.swing.JLabel();
        yearComboBox = new javax.swing.JComboBox();
        monthComboBox = new javax.swing.JComboBox();
        monthLabel = new javax.swing.JLabel();
        dayLabel = new javax.swing.JLabel();
        dayComboBox = new javax.swing.JComboBox();
        dateArrivedValueText = new javax.swing.JTextField();
        hyphen1Label = new javax.swing.JLabel();
        hyphen2Label = new javax.swing.JLabel();
        yearComboBox1 = new javax.swing.JComboBox();
        yearLabel1 = new javax.swing.JLabel();
        monthComboBox1 = new javax.swing.JComboBox();
        monthLabel1 = new javax.swing.JLabel();
        dayLabel1 = new javax.swing.JLabel();
        dayComboBox1 = new javax.swing.JComboBox();
        hyphen1Label1 = new javax.swing.JLabel();
        hyphen2Label1 = new javax.swing.JLabel();
        dateDepartedValueText = new javax.swing.JTextField();
        yearComboBox2 = new javax.swing.JComboBox();
        yearLabel2 = new javax.swing.JLabel();
        monthComboBox2 = new javax.swing.JComboBox();
        monthLabel2 = new javax.swing.JLabel();
        dayLabel2 = new javax.swing.JLabel();
        dayComboBox2 = new javax.swing.JComboBox();
        hyphen1Label2 = new javax.swing.JLabel();
        hyphen2Label2 = new javax.swing.JLabel();
        dateDeceasedValueText = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        backGroundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Animal External History Frame");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        animalExternalHistoryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Animal External History", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(102, 102, 255))); // NOI18N

        previousLocationLabel.setText("Previous Location:");

        dateArrivedLabel.setText("Date Arrived:");

        dateDepartedLabel.setText("Date Departed:");

        departedToLabel.setText("Departed to:");

        dateDeceasedLabel.setText("Date Deceased:");

        yearLabel.setText("YYYY");

        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "####", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014" }));
        yearComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearComboBoxItemStateChanged(evt);
            }
        });
        yearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearComboBoxActionPerformed(evt);
            }
        });

        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "##", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        monthComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monthComboBoxItemStateChanged(evt);
            }
        });

        monthLabel.setText("MM");

        dayLabel.setText("DD");

        dayComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "##", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dayComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dayComboBoxItemStateChanged(evt);
            }
        });

        hyphen1Label.setText("-");

        hyphen2Label.setText("-");

        yearComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "####", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014" }));
        yearComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearComboBox1ItemStateChanged(evt);
            }
        });
        yearComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearComboBox1ActionPerformed(evt);
            }
        });

        yearLabel1.setText("YYYY");

        monthComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "##", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        monthComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monthComboBox1ItemStateChanged(evt);
            }
        });

        monthLabel1.setText("MM");

        dayLabel1.setText("DD");

        dayComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "##", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dayComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dayComboBox1ItemStateChanged(evt);
            }
        });

        hyphen1Label1.setText("-");

        hyphen2Label1.setText("-");

        yearComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "####", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014" }));
        yearComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearComboBox2ItemStateChanged(evt);
            }
        });
        yearComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearComboBox2ActionPerformed(evt);
            }
        });

        yearLabel2.setText("YYYY");

        monthComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "##", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        monthComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monthComboBox2ItemStateChanged(evt);
            }
        });

        monthLabel2.setText("MM");

        dayLabel2.setText("DD");

        dayComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "##", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dayComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dayComboBox2ItemStateChanged(evt);
            }
        });

        hyphen1Label2.setText("-");

        hyphen2Label2.setText("-");

        submitButton.setText("Submit & Return");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout animalExternalHistoryPanelLayout = new javax.swing.GroupLayout(animalExternalHistoryPanel);
        animalExternalHistoryPanel.setLayout(animalExternalHistoryPanelLayout);
        animalExternalHistoryPanelLayout.setHorizontalGroup(
            animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(animalExternalHistoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(animalExternalHistoryPanelLayout.createSequentialGroup()
                        .addComponent(dateDepartedLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearLabel1)
                            .addGroup(animalExternalHistoryPanelLayout.createSequentialGroup()
                                .addComponent(yearComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hyphen1Label1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monthComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hyphen2Label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dayLabel1)
                            .addGroup(animalExternalHistoryPanelLayout.createSequentialGroup()
                                .addComponent(dayComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dateDepartedValueText, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(114, Short.MAX_VALUE))
                    .addGroup(animalExternalHistoryPanelLayout.createSequentialGroup()
                        .addComponent(previousLocationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previousLocationText, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(239, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, animalExternalHistoryPanelLayout.createSequentialGroup()
                        .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, animalExternalHistoryPanelLayout.createSequentialGroup()
                                .addComponent(dateArrivedLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yearLabel)
                                    .addGroup(animalExternalHistoryPanelLayout.createSequentialGroup()
                                        .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hyphen1Label)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(monthLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hyphen2Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dayLabel)
                                    .addGroup(animalExternalHistoryPanelLayout.createSequentialGroup()
                                        .addComponent(dayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(dateArrivedValueText, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, animalExternalHistoryPanelLayout.createSequentialGroup()
                                .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateDeceasedLabel)
                                    .addComponent(departedToLabel))
                                .addGap(8, 8, 8)
                                .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(departedToText, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                                    .addGroup(animalExternalHistoryPanelLayout.createSequentialGroup()
                                        .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(yearLabel2)
                                            .addGroup(animalExternalHistoryPanelLayout.createSequentialGroup()
                                                .addComponent(yearComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(hyphen1Label2)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(monthComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(monthLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hyphen2Label2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dayLabel2)
                                            .addGroup(animalExternalHistoryPanelLayout.createSequentialGroup()
                                                .addComponent(dayComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(closeButton)
                                                    .addComponent(dateDeceasedValueText, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))))
                                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(114, 114, 114))))
        );

        animalExternalHistoryPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dateArrivedLabel, dateDeceasedLabel, dateDepartedLabel, previousLocationLabel});

        animalExternalHistoryPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dateArrivedValueText, dateDepartedValueText});

        animalExternalHistoryPanelLayout.setVerticalGroup(
            animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(animalExternalHistoryPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousLocationLabel)
                    .addComponent(previousLocationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateArrivedLabel)
                    .addGroup(animalExternalHistoryPanelLayout.createSequentialGroup()
                        .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yearLabel)
                            .addComponent(monthLabel)
                            .addComponent(dayLabel))
                        .addGap(1, 1, 1)
                        .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hyphen1Label)
                            .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hyphen2Label)
                            .addComponent(dayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateArrivedValueText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateDepartedLabel)
                    .addGroup(animalExternalHistoryPanelLayout.createSequentialGroup()
                        .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yearLabel1)
                            .addComponent(monthLabel1)
                            .addComponent(dayLabel1))
                        .addGap(1, 1, 1)
                        .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yearComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hyphen1Label1)
                            .addComponent(monthComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hyphen2Label1)
                            .addComponent(dayComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateDepartedValueText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departedToLabel)
                    .addComponent(departedToText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel2)
                    .addComponent(monthLabel2)
                    .addComponent(dayLabel2))
                .addGap(1, 1, 1)
                .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hyphen1Label2)
                    .addComponent(monthComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hyphen2Label2)
                    .addComponent(dayComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateDeceasedValueText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateDeceasedLabel))
                .addGap(18, 18, 18)
                .addGroup(animalExternalHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(closeButton))
                .addContainerGap())
        );

        animalExternalHistoryPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dateArrivedLabel, dateDeceasedLabel, dateDepartedLabel, departedToLabel, previousLocationLabel});

        getContentPane().add(animalExternalHistoryPanel);
        animalExternalHistoryPanel.setBounds(50, 30, 520, 360);
        getContentPane().add(backGroundImageLabel);
        backGroundImageLabel.setBounds(0, 0, 620, 430);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-634)/2, (screenSize.height-470)/2, 634, 470);
    }// </editor-fold>//GEN-END:initComponents

    private void yearComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearComboBoxItemStateChanged
        Ayear = yearComboBox.getSelectedItem().toString();
        DOB=Ayear+"-"+Amonth+"-"+Aday;
        dateArrivedValueText.setText(DOB);
}//GEN-LAST:event_yearComboBoxItemStateChanged

    private void yearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_yearComboBoxActionPerformed

    private void monthComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monthComboBoxItemStateChanged
        Amonth = monthComboBox.getSelectedItem().toString();
        DOB=Ayear+"-"+Amonth+"-"+Aday;
        dateArrivedValueText.setText(DOB);
}//GEN-LAST:event_monthComboBoxItemStateChanged

    private void dayComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dayComboBoxItemStateChanged
        Aday = dayComboBox.getSelectedItem().toString();
        DOB=Ayear+"-"+Amonth+"-"+Aday;
        dateArrivedValueText.setText(DOB);
}//GEN-LAST:event_dayComboBoxItemStateChanged

    private void yearComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearComboBox1ItemStateChanged
        Ayear = yearComboBox1.getSelectedItem().toString();
        DOB=Ayear+"-"+Amonth+"-"+Aday;
        dateDepartedValueText.setText(DOB);
    }//GEN-LAST:event_yearComboBox1ItemStateChanged

    private void yearComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearComboBox1ActionPerformed

    private void monthComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monthComboBox1ItemStateChanged
        Amonth = monthComboBox1.getSelectedItem().toString();
        DOB=Ayear+"-"+Amonth+"-"+Aday;
        dateDepartedValueText.setText(DOB);
    }//GEN-LAST:event_monthComboBox1ItemStateChanged

    private void dayComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dayComboBox1ItemStateChanged
        Aday = dayComboBox1.getSelectedItem().toString();
        DOB=Ayear+"-"+Amonth+"-"+Aday;
        dateDepartedValueText.setText(DOB);
    }//GEN-LAST:event_dayComboBox1ItemStateChanged

    private void yearComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearComboBox2ItemStateChanged
        Ayear = yearComboBox2.getSelectedItem().toString();
        DOB=Ayear+"-"+Amonth+"-"+Aday;
        dateDeceasedValueText.setText(DOB);
    }//GEN-LAST:event_yearComboBox2ItemStateChanged

    private void yearComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearComboBox2ActionPerformed

    private void monthComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monthComboBox2ItemStateChanged
        Amonth = monthComboBox2.getSelectedItem().toString();
        DOB=Ayear+"-"+Amonth+"-"+Aday;
        dateDeceasedValueText.setText(DOB);
    }//GEN-LAST:event_monthComboBox2ItemStateChanged

    private void dayComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dayComboBox2ItemStateChanged
        Aday = dayComboBox2.getSelectedItem().toString();
        DOB=Ayear+"-"+Amonth+"-"+Aday;
        dateDeceasedValueText.setText(DOB);
    }//GEN-LAST:event_dayComboBox2ItemStateChanged

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String url = "jdbc:mysql://127.0.0.1:3306/";
        String dbName = "zooProject";
        String driver = "com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "nss2013";


//        {
//            departedToText.setNull(java.sql.Types.VARCHAR);
//        }
//        if(dateDepartedValueText.getText() == null)
//        {
//            dateDepartedValueText.setText("");
//        }
//        if(dateDeceasedValueText.getText() == null)
//        {
//            dateDeceasedValueText.setText("");
//        }

        try {
            Class.forName(driver).newInstance();
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            System.out.println("Database Connection Successful");

            String sql = "INSERT INTO ANIMAL_LOC_HIST(PREV_LOCATION, DATE_ARRIVED, DATE_DEPARTED, DEPARTED_TO, DATE_DECEASED)" +
                         "VALUES(?, ?, ?, ?, ?)";
            // Set up a create statement
            prest = conn.prepareStatement(sql);
            // Set Up SQL
            prest.setString(1, previousLocationText.getText());
            prest.setString(2, dateArrivedValueText.getText());
            prest.setString(3, dateDepartedValueText.getText());
            if(dateDepartedValueText.getText() == null)
            {
                prest.setNull(3, java.sql.Types.DATE);
            }
            else if(dateDepartedValueText.getText().equals(""))
            {
                prest.setNull(3, java.sql.Types.DATE);
            }

            prest.setString(4, departedToText.getText());
            if(departedToText.getText() == null)
            {
                prest.setNull(4, java.sql.Types.VARCHAR);
            }
            else if(departedToText.getText().equals(""))
            {
                prest.setNull(4, java.sql.Types.VARCHAR);
            }

            prest.setString(5, dateDeceasedValueText.getText());
            if(dateDeceasedValueText.getText() == null)
            {
                prest.setNull(5, java.sql.Types.DATE);
            }
            else if(dateDeceasedValueText.getText().equals(""))
            {
                prest.setNull(5, java.sql.Types.DATE);
            }
            prest.executeUpdate();
            JOptionPane.showMessageDialog(null, "New Animal History has been created for this Animal");

            // Close the connection to the database
            conn.close();
            prest.close();
        } catch (Exception e) {
            e.printStackTrace();
        }





        try {
            Class.forName(driver).newInstance();

            System.out.println("Connecting to the Database " + dbName + "....");
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            System.out.println("Database Connection Successful");

                // Set up a create statement
              java.sql.Statement stmn = conn.createStatement();
              // Set Up SQL
              String sql = "SELECT * FROM ANIMAL_LOC_HIST " +
                           "WHERE ANIMAL_HIST_ID = (SELECT MAX(ANIMAL_HIST_ID) FROM ANIMAL_LOC_HIST)";
              // Excute Query and send result set to rs
              ResultSet rs = stmn.executeQuery(sql);
            while (rs.next()) {
                // Retrieve by column name
                String PREV_LOCATION = rs.getString("PREV_LOCATION");
                newAnimalEntryFrame.birthLocationText.setText(PREV_LOCATION);
            }
            // Close the connection to the database
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        setVisible(false);
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimalExternalHistoryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel animalExternalHistoryPanel;
    private javax.swing.JLabel backGroundImageLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel dateArrivedLabel;
    private javax.swing.JTextField dateArrivedValueText;
    private javax.swing.JLabel dateDeceasedLabel;
    private javax.swing.JTextField dateDeceasedValueText;
    private javax.swing.JLabel dateDepartedLabel;
    private javax.swing.JTextField dateDepartedValueText;
    private javax.swing.JComboBox dayComboBox;
    private javax.swing.JComboBox dayComboBox1;
    private javax.swing.JComboBox dayComboBox2;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JLabel dayLabel1;
    private javax.swing.JLabel dayLabel2;
    private javax.swing.JLabel departedToLabel;
    private javax.swing.JTextField departedToText;
    private javax.swing.JLabel hyphen1Label;
    private javax.swing.JLabel hyphen1Label1;
    private javax.swing.JLabel hyphen1Label2;
    private javax.swing.JLabel hyphen2Label;
    private javax.swing.JLabel hyphen2Label1;
    private javax.swing.JLabel hyphen2Label2;
    private javax.swing.JComboBox monthComboBox;
    private javax.swing.JComboBox monthComboBox1;
    private javax.swing.JComboBox monthComboBox2;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JLabel monthLabel1;
    private javax.swing.JLabel monthLabel2;
    private javax.swing.JLabel previousLocationLabel;
    private javax.swing.JTextField previousLocationText;
    private javax.swing.JButton submitButton;
    private javax.swing.JComboBox yearComboBox;
    private javax.swing.JComboBox yearComboBox1;
    private javax.swing.JComboBox yearComboBox2;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JLabel yearLabel1;
    private javax.swing.JLabel yearLabel2;
    // End of variables declaration//GEN-END:variables

}
