/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * cleanerFeederFrame.java
 *
 * Created on 25-Feb-2014, 21:49:06
 */

package my.zooProjectPackage;
/**
 *
 * @author patrick
 */
public class cleanerFeederOptionsFrame extends javax.swing.JFrame {
    

    /** Creates new form cleanerFeederFrame */
    public cleanerFeederOptionsFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchRecordsButton = new javax.swing.JButton();
        feedingLogButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CleanerFeeder Options Frame");
        setMinimumSize(new java.awt.Dimension(512, 400));
        getContentPane().setLayout(null);

        searchRecordsButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14));
        searchRecordsButton.setText("Search Records");
        searchRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRecordsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchRecordsButton);
        searchRecordsButton.setBounds(40, 210, 190, 40);

        feedingLogButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14));
        feedingLogButton.setText("Habitat / Feeding Log");
        feedingLogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedingLogButtonActionPerformed(evt);
            }
        });
        getContentPane().add(feedingLogButton);
        feedingLogButton.setBounds(40, 90, 190, 40);

        logOutButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14));
        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logOutButton);
        logOutButton.setBounds(400, 330, 90, 27);

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/babyRhino(Edited).jpg"))); // NOI18N
        backgroundImage.setMaximumSize(new java.awt.Dimension(600, 500));
        getContentPane().add(backgroundImage);
        backgroundImage.setBounds(0, 0, 500, 360);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-518)/2, (screenSize.height-399)/2, 518, 399);
    }// </editor-fold>//GEN-END:initComponents

    private void searchRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRecordsButtonActionPerformed
        // This code changes the header text to show the below text in quotes and removes the Staff option from the dropdown list. 
        searchUpdateDeleteFrame frame = new searchUpdateDeleteFrame();
        frame.setVisible(true);
        frame.chooseTableComboBox.removeItem("Staff");
        frame.updateTableButton.setVisible(false);
        frame.deleteButton.setVisible(false);
        frame.searchResultsHeadingLabel.setText("   CleanerFeeder Search Results");
        setVisible(false);
}//GEN-LAST:event_searchRecordsButtonActionPerformed


    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // When this button is clicked a New Frame Object called Frame is created & the User
        // is returned to the Main login Frame.
        loginFrame frame = new loginFrame();
        frame.setVisible(true);
        setVisible(false);
}//GEN-LAST:event_logOutButtonActionPerformed


    private void feedingLogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedingLogButtonActionPerformed
        // When this button is clicked a New Frame Object called Frame is created & the User
        // is returned to the Main login Frame.
        cleanFeedLogFrame frame = new cleanFeedLogFrame();
        frame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_feedingLogButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cleanerFeederOptionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JButton feedingLogButton;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton searchRecordsButton;
    // End of variables declaration//GEN-END:variables

}