package my.zooProjectPackage;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 * Dublin Zoo Joint Project.
 * @author Will Hogan
 * Created 24/02/2014
 */
public class loginFrame extends javax.swing.JFrame {

    

    /** Creates new form loginFrame */
    public loginFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        staffLoginPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordFieldText = new javax.swing.JPasswordField();
        titleLabel = new javax.swing.JLabel();
        titleComboBox = new javax.swing.JComboBox();
        exitButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Frame");
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(672, 391));
        setResizable(false);
        getContentPane().setLayout(null);

        staffLoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        staffLoginPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Staff Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(153, 153, 255))); // NOI18N

        usernameLabel.setFont(new java.awt.Font("Arial", 0, 11));
        usernameLabel.setText("Username:");

        passwordLabel.setFont(new java.awt.Font("Arial", 0, 11));
        passwordLabel.setText("Password:");

        titleLabel.setText("Title:");

        titleComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please Select...", "Manager", "Vet", "CleanerFeeder" }));

        javax.swing.GroupLayout staffLoginPanelLayout = new javax.swing.GroupLayout(staffLoginPanel);
        staffLoginPanel.setLayout(staffLoginPanelLayout);
        staffLoginPanelLayout.setHorizontalGroup(
            staffLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffLoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staffLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffLoginPanelLayout.createSequentialGroup()
                        .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(staffLoginPanelLayout.createSequentialGroup()
                        .addGroup(staffLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(staffLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleComboBox, 0, 154, Short.MAX_VALUE)
                            .addComponent(passwordFieldText, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))))
                .addGap(40, 40, 40))
        );

        staffLoginPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {passwordLabel, titleLabel, usernameLabel});

        staffLoginPanelLayout.setVerticalGroup(
            staffLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffLoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staffLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(staffLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(staffLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(titleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(staffLoginPanel);
        staffLoginPanel.setBounds(330, 10, 300, 140);

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(440, 340, 73, 20);

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(440, 160, 73, 23);

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/dublin-zoo-image(editedJPEG).jpg"))); // NOI18N
        backgroundImage.setLabelFor(backgroundImage);
        getContentPane().add(backgroundImage);
        backgroundImage.setBounds(0, 0, 672, 362);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-688)/2, (screenSize.height-399)/2, 688, 399);
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // Closes the Frame when the Close button is Clicked.
        setVisible(false);
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
            // This part deals with the Variables associated with the Database Connection
            String url = "jdbc:mysql://127.0.0.1:3306/";
            String dbName = "zooProject";
            String driver = "com.mysql.jdbc.Driver";
            String userName = "root";
            String password = "nss2013";

            // This parts tries to execute the SQL statement and if it can't relays a message
            // The first section is connecting the various variables to the statement to be exectuted
            try
            {
               Class.forName(driver).newInstance();
               Connection conn = DriverManager.getConnection(url + dbName, userName, password);
               System.out.println("Database Connection Successful");

               Class.forName("com.mysql.jdbc.Driver");
               Statement stmn = conn.createStatement();

               // Variables used in the SQL Statement
               String user = usernameText.getText().toString();
               String pass = passwordFieldText.getText().toString();
               String title = titleComboBox.getSelectedItem().toString();

              // This is the actual SQL statement to be executed
               ResultSet rs = stmn.executeQuery("SELECT * FROM STAFF_LOGIN_VIEW WHERE USERNAME = '"+user+"' AND PASSWORD = '"+pass+"' AND TITLE = '"+title+"'");

                // The various criteria that is required by each type of employee
                if(rs.next())
                {
                    if(titleComboBox.getSelectedItem().equals("Manager"))
                    {
                        JOptionPane.showMessageDialog(null, "Manager Login Successful");
                        managersOptionsFrame frame =  new managersOptionsFrame();
                        frame.setVisible(true);
                        setVisible(false);
                    }
                    else if(titleComboBox.getSelectedItem().equals("Vet"))
                    {
                        JOptionPane.showMessageDialog(null, "Vet Login Successful");
                        vetOptionsFrame frame = new vetOptionsFrame();
                        frame.setVisible(true);
                        setVisible(false);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "CleanerFeeder Login Successful");
                        cleanerFeederOptionsFrame frame = new cleanerFeederOptionsFrame();
                        frame.setVisible(true);
                        setVisible(false);
                    }
                }
                else
                {
                   // If full details have not been entered, display the below message.
                   JOptionPane.showMessageDialog(null,"Invalid Login Details.");
                   usernameText.setText("");
                   passwordFieldText.setText("");
                   titleComboBox.setSelectedItem("Please Select...");
                }
                   conn.close();
            }
              catch (Exception e)
            {
              e.printStackTrace();
            }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordFieldText;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel staffLoginPanel;
    private javax.swing.JComboBox titleComboBox;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables

}