/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * newTaxonomyEntryFrame.java
 *
 * Created on 08-Mar-2014, 21:24:32
 */

package my.zooProjectPackage;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author patrick
 */
public class newTaxonomyEntryFrame extends javax.swing.JFrame {

    private PreparedStatement prest;
    /** Creates new form newTaxonomyEntryFrame */
    public newTaxonomyEntryFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newTaxonomyEntryPanel = new javax.swing.JPanel();
        speciesLabel = new javax.swing.JLabel();
        familyLabel = new javax.swing.JLabel();
        orderLabel = new javax.swing.JLabel();
        classLabel = new javax.swing.JLabel();
        phylumLabel = new javax.swing.JLabel();
        kingdomLabel = new javax.swing.JLabel();
        speciesNameText = new javax.swing.JTextField();
        familyNameText = new javax.swing.JTextField();
        orderNameText = new javax.swing.JTextField();
        classNameText = new javax.swing.JTextField();
        phylumNameText = new javax.swing.JTextField();
        kingdomNameText = new javax.swing.JTextField();
        createNewTaxonomyButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        backgroundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Taxonomy Entry Frame");
        setMinimumSize(new java.awt.Dimension(425, 410));
        getContentPane().setLayout(null);

        newTaxonomyEntryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Taxonomy Entry", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(102, 102, 255))); // NOI18N

        speciesLabel.setText("Species:");

        familyLabel.setText("Family:");

        orderLabel.setText("Order:");

        classLabel.setText("Class:");

        phylumLabel.setText("Phylum:");

        kingdomLabel.setText("Kingdom:");

        kingdomNameText.setText("Animal");

        createNewTaxonomyButton.setText("Create New Taxonomy");
        createNewTaxonomyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewTaxonomyButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newTaxonomyEntryPanelLayout = new javax.swing.GroupLayout(newTaxonomyEntryPanel);
        newTaxonomyEntryPanel.setLayout(newTaxonomyEntryPanelLayout);
        newTaxonomyEntryPanelLayout.setHorizontalGroup(
            newTaxonomyEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newTaxonomyEntryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newTaxonomyEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newTaxonomyEntryPanelLayout.createSequentialGroup()
                        .addComponent(speciesLabel)
                        .addGap(18, 18, 18)
                        .addComponent(speciesNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newTaxonomyEntryPanelLayout.createSequentialGroup()
                        .addComponent(familyLabel)
                        .addGap(18, 18, 18)
                        .addComponent(familyNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newTaxonomyEntryPanelLayout.createSequentialGroup()
                        .addGroup(newTaxonomyEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderLabel)
                            .addComponent(classLabel))
                        .addGap(18, 18, 18)
                        .addGroup(newTaxonomyEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(newTaxonomyEntryPanelLayout.createSequentialGroup()
                        .addGroup(newTaxonomyEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phylumLabel)
                            .addComponent(kingdomLabel))
                        .addGap(18, 18, 18)
                        .addGroup(newTaxonomyEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kingdomNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phylumNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(newTaxonomyEntryPanelLayout.createSequentialGroup()
                                .addComponent(createNewTaxonomyButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        newTaxonomyEntryPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {classNameText, familyNameText, kingdomNameText, orderNameText, phylumNameText, speciesNameText});

        newTaxonomyEntryPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {classLabel, familyLabel, kingdomLabel, orderLabel, phylumLabel, speciesLabel});

        newTaxonomyEntryPanelLayout.setVerticalGroup(
            newTaxonomyEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newTaxonomyEntryPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(newTaxonomyEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speciesLabel)
                    .addComponent(speciesNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newTaxonomyEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(familyLabel)
                    .addComponent(familyNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newTaxonomyEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderLabel)
                    .addComponent(orderNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newTaxonomyEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classLabel)
                    .addComponent(classNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newTaxonomyEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phylumLabel)
                    .addComponent(phylumNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newTaxonomyEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kingdomLabel)
                    .addComponent(kingdomNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newTaxonomyEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createNewTaxonomyButton)
                    .addComponent(jButton1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(newTaxonomyEntryPanel);
        newTaxonomyEntryPanel.setBounds(30, 20, 350, 330);
        getContentPane().add(backgroundImageLabel);
        backgroundImageLabel.setBounds(0, 0, 570, 460);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-431)/2, (screenSize.height-416)/2, 431, 416);
    }// </editor-fold>//GEN-END:initComponents

    private void createNewTaxonomyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewTaxonomyButtonActionPerformed
        String url = "jdbc:mysql://127.0.0.1:3306/";
        String dbName = "zooProject";
        String driver = "com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "nss2013";


        try {
            Class.forName(driver).newInstance();

            System.out.println("Connecting to the Database " + dbName + "....");
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            System.out.println("Database Connection Successful");

            String sql = "INSERT INTO TAXONOMY(SPECIES, FAMILY, ORDERING, CLASS, PHYLUM, KINGDOM)" +
                         " VALUES(?, ?, ?, ?, ?, ?)";
            // Set up a create statement
            prest = conn.prepareStatement(sql);
            // Set Up SQL
            prest.setString(1, speciesNameText.getText());
            prest.setString(2, familyNameText.getText());
            prest.setString(3, orderNameText.getText());
            prest.setString(4, classNameText.getText());
            prest.setString(5, phylumNameText.getText());
            prest.setString(6, kingdomNameText.getText());
            prest.executeUpdate();

            JOptionPane.showMessageDialog(null, "A new Taxonomy has been Created For this Animal");

            // Close the connection to the database
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        
        try {
            Class.forName(driver).newInstance();

            System.out.println("Connecting to the Database " + dbName + "....");
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            System.out.println("Database Connection Successful");

                // Set up a create statement
              java.sql.Statement stmn = conn.createStatement();
              // Set Up SQL
              String sql = "SELECT * FROM TAXONOMY WHERE TAXON_CODE = (SELECT MAX(TAXON_CODE) FROM TAXONOMY)";
              // Excute Query and send result set to rs
              ResultSet rs = stmn.executeQuery(sql);
            while (rs.next()) {
                // Retrieve by column name
                String TAXON_CODE = rs.getString("TAXON_CODE");
                String SPECIES = rs.getString("SPECIES");
                String FAMILY = rs.getString("FAMILY");
                String ORDERING = rs.getString("ORDERING");
                String CLASS = rs.getString("CLASS");
                String PHYLUM = rs.getString("PHYLUM");
                String KINGDOM = rs.getString("KINGDOM");
                newAnimalEntryFrame.taxonomyCodeComboBox.addItem(TAXON_CODE);
                newAnimalEntryFrame.taxonomyCodeComboBox.setSelectedItem(TAXON_CODE);
                newAnimalEntryFrame.speciesTaxonomyText.setText(SPECIES);
                newAnimalEntryFrame.familyTaxonomyText.setText(FAMILY);
                newAnimalEntryFrame.orderTaxonomyText.setText(ORDERING);
                newAnimalEntryFrame.classTaxonomyText.setText(CLASS);
                newAnimalEntryFrame.phylumTaxonomyText.setText(PHYLUM);
                newAnimalEntryFrame.kingdomTaxonomyText.setText(KINGDOM);
            }
            // Close the connection to the database
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        setVisible(false);
        dispose();
    }//GEN-LAST:event_createNewTaxonomyButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newTaxonomyEntryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImageLabel;
    private javax.swing.JLabel classLabel;
    private javax.swing.JTextField classNameText;
    private javax.swing.JButton createNewTaxonomyButton;
    private javax.swing.JLabel familyLabel;
    private javax.swing.JTextField familyNameText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel kingdomLabel;
    private javax.swing.JTextField kingdomNameText;
    private javax.swing.JPanel newTaxonomyEntryPanel;
    private javax.swing.JLabel orderLabel;
    private javax.swing.JTextField orderNameText;
    private javax.swing.JLabel phylumLabel;
    private javax.swing.JTextField phylumNameText;
    private javax.swing.JLabel speciesLabel;
    private javax.swing.JTextField speciesNameText;
    // End of variables declaration//GEN-END:variables

}
