/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * vetOptionsFrame.java
 *
 * Created on 25-Feb-2014, 21:35:39
 */

package my.zooProjectPackage;
/**
 *
 * @author patrick
 */
public class vetOptionsFrame extends javax.swing.JFrame {

    /** Creates new form vetOptionsFrame */
    public vetOptionsFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExaminationLogButton = new javax.swing.JButton();
        searchRecordsButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vet Options Frame");
        setMinimumSize(new java.awt.Dimension(512, 400));
        getContentPane().setLayout(null);

        ExaminationLogButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14));
        ExaminationLogButton.setText("Log an Examination");
        ExaminationLogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExaminationLogButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExaminationLogButton);
        ExaminationLogButton.setBounds(40, 90, 180, 40);

        searchRecordsButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14));
        searchRecordsButton.setText("Search Records");
        searchRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRecordsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchRecordsButton);
        searchRecordsButton.setBounds(40, 210, 180, 40);

        logOutButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14));
        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logOutButton);
        logOutButton.setBounds(400, 330, 90, 27);

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/babyRhino(Edited).jpg"))); // NOI18N
        backgroundImage.setMaximumSize(new java.awt.Dimension(600, 500));
        getContentPane().add(backgroundImage);
        backgroundImage.setBounds(0, 0, 500, 360);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-516)/2, (screenSize.height-400)/2, 516, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void searchRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRecordsButtonActionPerformed
        // This code changes the header text to show the below text in quotes and removes the Staff option from the dropdown list. 
        searchUpdateDeleteFrame frame = new searchUpdateDeleteFrame();
        frame.setVisible(true);
        frame.searchResultsHeadingLabel.setText("            Vet Search Results");
        frame.chooseTableComboBox.removeItem("Staff");
        frame.updateTableButton.setVisible(false);
        frame.deleteButton.setVisible(false);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_searchRecordsButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // When this button is clicked a New Frame Object called Frame is created & the User
        // is returned to the Main login Frame.
        loginFrame frame = new loginFrame();
        frame.setVisible(true);
        setVisible(false);
}//GEN-LAST:event_logOutButtonActionPerformed

    private void ExaminationLogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExaminationLogButtonActionPerformed
        // When this button is clicked a New Frame Object called Frame is created & the User
        // is returned to the Main login Frame.
        vetExaminationLogFrame frame = new vetExaminationLogFrame();
        frame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ExaminationLogButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vetOptionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExaminationLogButton;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton searchRecordsButton;
    // End of variables declaration//GEN-END:variables

}
